analyzed_value = input('Type something')
print('The value type was classified as:', type(analyzed_value))
print('value typed is alphanumeric true/false:', analyzed_value.isalnum())
print('value typed is alphabetic true/false:', analyzed_value.isalpha())
print('value typed is a number true/false:', analyzed_value.isnumeric())
print('value typed is ascii true/false:', analyzed_value.isascii())
print('value typed is a digit true/false:', analyzed_value.isdigit())
print('value typed is a decimal number true/false:', analyzed_value.isdecimal())
print('value typed is lowercase true/false:', analyzed_value.islower())
print('value typed is al uppercase true/false:', analyzed_value.isupper())
print('value typed is a valid identifier true/false:', analyzed_value.isidentifier())
print('value typed is printable true/false:', analyzed_value.isprintable())
print('value typed is a whitespace true/false:', analyzed_value.isspace())
print('value typed is a title true/false:', analyzed_value.istitle())
